import { access, mkdir, readFile, writeFile } from "node:fs/promises";

const root = new URL("../", import.meta.url);
const masterPath = new URL("assets/openbindings-glyph.svg", root);
const generatedDirectory = new URL("assets/generated/", root);
const master = (await readFile(masterPath, "utf8")).trim();

const expectedViewBox = 'viewBox="102 62 978 1066"';
const pathCount = (master.match(/<path\b/g) ?? []).length;
const currentColorCount = (master.match(/stroke="currentColor"/g) ?? []).length;

if (!master.includes(expectedViewBox)) {
  throw new Error(`canonical glyph must retain ${expectedViewBox}`);
}
if (pathCount !== 5 || currentColorCount !== pathCount) {
  throw new Error("canonical glyph must contain five currentColor paths");
}
if (/<(?:style|title|desc)\b/.test(master)) {
  throw new Error("canonical glyph must remain presentation- and context-neutral");
}

const notice = [
  "<!-- Generated from openbindings/design/assets/openbindings-glyph.svg.",
  "     Identity revision 1. Do not edit this file by hand. -->",
].join("\n");

const inline = `${notice}\n${master}\n`;
const faviconStyle = [
  "<style>",
  "  path { stroke: white; }",
  "  @media (prefers-color-scheme: light) {",
  "    path { stroke: black; }",
  "  }",
  "</style>",
].join("\n");
const favicon = `${notice}\n${master.replace(">", `>\n${faviconStyle}`)}\n`;

const outputs = new Map([
  [new URL("openbindings-glyph.svg", generatedDirectory), inline],
  [new URL("favicon.svg", generatedDirectory), favicon],
]);

if (process.argv.includes("--check")) {
  for (const [path, expected] of outputs) {
    await access(path);
    const actual = await readFile(path, "utf8");
    if (actual !== expected) {
      throw new Error(`${path.pathname} is stale; run npm run generate`);
    }
  }
  console.log(`asset check: ${outputs.size} generated variants current`);
} else {
  await mkdir(generatedDirectory, { recursive: true });
  await Promise.all([...outputs].map(([path, contents]) => writeFile(path, contents)));
  console.log(`generated ${outputs.size} identity variants`);
}
